---
site_name: SQL Learning Materials
site_url: https://github.com/Bilbottom/sql-learning-materials/docs/
site_description: SQL scripts that demonstrate various features and concepts.
site_author: Bilbottom
repo_url: https://github.com/Bilbottom/sql-learning-materials/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
  palette:
    - accent: default
      primary: default
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - accent: default
      primary: default
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - From Excel to SQL:
      - from-excel-to-sql/from-excel-to-sql.md
      - Getting Started:
          - from-excel-to-sql/getting-started/setting-the-context.md
          - from-excel-to-sql/getting-started/sql-syntax.md
      - Main Concepts:
          - from-excel-to-sql/main-concepts/select-and-from.md
          - from-excel-to-sql/main-concepts/where.md
          - from-excel-to-sql/main-concepts/order-by.md
          - from-excel-to-sql/main-concepts/comments.md
          - from-excel-to-sql/main-concepts/top-and-distinct.md
          - from-excel-to-sql/main-concepts/data-types.md
          - from-excel-to-sql/main-concepts/operators.md
          - from-excel-to-sql/main-concepts/conditionals.md
          - from-excel-to-sql/main-concepts/date-formatting.md
          - from-excel-to-sql/main-concepts/group-by.md
          - from-excel-to-sql/main-concepts/rollup.md
          - from-excel-to-sql/main-concepts/join.md
          - from-excel-to-sql/main-concepts/union.md
          - from-excel-to-sql/main-concepts/subqueries.md
          - from-excel-to-sql/main-concepts/window-functions.md
          - from-excel-to-sql/main-concepts/logical-processing-order.md
          - from-excel-to-sql/main-concepts/style-guide.md
      - Advanced Concepts:
          - from-excel-to-sql/advanced-concepts/advanced-aggregations.md
          - from-excel-to-sql/advanced-concepts/correlated-subqueries.md
          - from-excel-to-sql/advanced-concepts/recursive-ctes.md
  - Everything about joins:
      - everything-about-joins/everything-about-joins.md
      - Syntax:
          - everything-about-joins/syntax/join-fundamentals.md
          - everything-about-joins/syntax/more-fundamentals.md
          - everything-about-joins/syntax/timestamp-joins.md
          - everything-about-joins/syntax/filtering-joins.md
          - everything-about-joins/syntax/glue-joins.md
          - everything-about-joins/syntax/explosive-joins.md
          - everything-about-joins/syntax/sql-92-rant.md
      - Under the hood:
          - everything-about-joins/under-the-hood/joins-with-an-index.md
          - everything-about-joins/under-the-hood/join-order.md
          - everything-about-joins/under-the-hood/loop-joins.md
          - everything-about-joins/under-the-hood/hash-joins.md
          - everything-about-joins/under-the-hood/merge-joins.md
          - everything-about-joins/under-the-hood/range-intersection-joins.md
  - Challenging SQL problems:
      - challenging-sql-problems/challenging-sql-problems.md
      - Problems:
          - ðŸŸ¤ Bronze Tier:
              - challenging-sql-problems/problems/bronze/fibonacci-sequence.md # recursive CTE
              - challenging-sql-problems/problems/bronze/temperature-anomaly-detection.md # window functions
              - challenging-sql-problems/problems/bronze/uk-bank-holidays.md #  unpivot and unnest
          - âšª Silver Tier:
              - challenging-sql-problems/problems/silver/suspicious-login-activity.md # window function (gaps and islands)
              - challenging-sql-problems/problems/silver/funnel-analytics.md # custom axis (TODO: this might be bronze tier)
              - challenging-sql-problems/problems/silver/customer-sales-running-totals.md # window functions
          - ðŸŸ¡ Gold Tier:
              - challenging-sql-problems/problems/gold/loan-repayment-schedule.md # recursive CTE
              - challenging-sql-problems/problems/gold/travel-plans.md # recursive CTEs
      - Solutions:
          - ðŸŸ¤ Bronze Tier:
              - challenging-sql-problems/solutions/bronze/fibonacci-sequence.md
              - challenging-sql-problems/solutions/bronze/temperature-anomaly-detection.md
              - challenging-sql-problems/solutions/bronze/uk-bank-holidays.md
          - âšª Silver Tier:
              - challenging-sql-problems/solutions/silver/suspicious-login-activity.md
              - challenging-sql-problems/solutions/silver/funnel-analytics.md
              - challenging-sql-problems/solutions/silver/customer-sales-running-totals.md
          - ðŸŸ¡ Gold Tier:
              - challenging-sql-problems/solutions/gold/loan-repayment-schedule.md
              - challenging-sql-problems/solutions/gold/travel-plans.md

markdown_extensions:
  - admonition
  - callouts # https://github.com/oprypin/markdown-callouts
  - mdx_truly_sane_lists # Support nested lists
  - pymdownx.details # Support collapsible sections with ???
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - { name: mermaid, class: mermaid }

plugins:
  - search
  - callouts # https://github.com/sondregronas/mkdocs-callouts
